"""Windows desktop guide for human-led agentic GitHub workflows.

The app is intentionally conservative: it can launch trusted tools and copy
commands for the user, but every operating-system action is initiated by an
explicit button press. It does not read secrets, credential stores, SSH keys, or
private environment files, and it does not merge pull requests automatically.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
import shutil
import subprocess
import sys
import webbrowser


@dataclass(frozen=True)
class WorkflowStep:
    """A single guided step in the Windows onboarding workflow."""

    title: str
    goal: str
    human_action: str
    genai_action: str
    command: str | None = None
    url: str | None = None
    automation: str | None = None


WORKFLOW_STEPS: tuple[WorkflowStep, ...] = (
    WorkflowStep(
        title="1. Install GitHub access tools",
        goal="Ensure Git, GitHub CLI, and authenticated GitHub access are available.",
        human_action="Install Git for Windows and GitHub CLI, then run the auth command in a terminal.",
        genai_action="Explain what each installer does and verify tool availability with the user.",
        command="gh auth login --web --git-protocol https",
        url="https://cli.github.com/",
        automation="Open the GitHub CLI download page and copy the login command.",
    ),
    WorkflowStep(
        title="2. Clone or open the target repository",
        goal="Put the code on the workstation in a folder the user controls.",
        human_action="Choose the repository URL and local folder, then clone or open the folder.",
        genai_action="Recommend a safe branch name and confirm the repo status before editing.",
        command="gh repo clone OWNER/REPO && cd REPO && git checkout -b genai/workflow-change",
        automation="Copy a clone-and-branch template the user can edit before running.",
    ),
    WorkflowStep(
        title="3. Install Claude CLI",
        goal="Make an approved coding agent available from the developer terminal.",
        human_action="Install Claude CLI using the organization-approved installation path.",
        genai_action="Help interpret installer output and confirm the CLI runs without exposing tokens.",
        command="claude --version",
        url="https://docs.anthropic.com/en/docs/claude-code/overview",
        automation="Open Claude Code documentation and copy a version-check command.",
    ),
    WorkflowStep(
        title="4. Open Visual Studio IDE",
        goal="Review code, tests, and agent changes in the IDE before committing.",
        human_action="Open the solution or folder in Visual Studio and keep source control visible.",
        genai_action="Suggest the smallest safe change, tests to run, and files to inspect.",
        command="devenv .",
        automation="Launch Visual Studio if devenv is on PATH, otherwise open the current folder.",
    ),
    WorkflowStep(
        title="5. Run an agentic coding loop",
        goal="Use GenAI to propose, implement, and review a bounded change.",
        human_action="Approve the task, inspect the diff, run tests, and decide whether to continue.",
        genai_action="Generate the patch, run checks, summarize risks, and perform a self-review.",
        command="git status && git diff --stat && claude",
        automation="Copy a status-and-agent command sequence for the integrated terminal.",
    ),
    WorkflowStep(
        title="6. Create, review, and merge the pull request",
        goal="Produce a PR generated by GenAI, reviewed by GenAI and the human, then merged by an authorized user.",
        human_action="Read the PR, validate checks, request/perform review, and explicitly approve merge to master.",
        genai_action="Draft PR title/body, review the final diff, and call out merge risks.",
        command="gh pr create --fill && gh pr checks --watch && gh pr review --comment --body \"GenAI review completed; human approval still required.\"",
        automation="Copy PR creation and review commands; merge remains a separate human-approved action.",
    ),
)


def build_workflow_summary() -> str:
    """Return a plain-text workflow summary for CLI and tests."""

    lines: list[str] = ["Windows Agentic Coding Guide", ""]
    for step in WORKFLOW_STEPS:
        lines.extend(
            [
                step.title,
                f"Goal: {step.goal}",
                f"Human: {step.human_action}",
                f"GenAI: {step.genai_action}",
            ]
        )
        if step.command:
            lines.append(f"Command: {step.command}")
        if step.automation:
            lines.append(f"Automation: {step.automation}")
        lines.append("")
    return "\n".join(lines).rstrip()


def _launch_visual_studio() -> str:
    devenv = shutil.which("devenv")
    if devenv:
        subprocess.Popen([devenv, os.getcwd()])  # noqa: S603 - user-triggered local IDE launch
        return "Launched Visual Studio with the current folder."
    if sys.platform.startswith("win"):
        os.startfile(os.getcwd())  # type: ignore[attr-defined]  # noqa: S606 - user-triggered folder open
        return "Visual Studio was not on PATH; opened the current folder instead."
    return "Visual Studio launch is only available on Windows."


def run_app() -> int:
    """Start the Tkinter Windows guide."""

    import tkinter as tk
    from tkinter import messagebox

    root = tk.Tk()
    root.title("Factory Fit Profiler - Windows Agentic Coding Guide")
    root.geometry("900x620")

    selected = tk.IntVar(value=0)
    title = tk.StringVar()
    body = tk.StringVar()
    command = tk.StringVar()

    def render() -> None:
        step = WORKFLOW_STEPS[selected.get()]
        title.set(step.title)
        body.set(f"Goal: {step.goal}\n\nHuman action: {step.human_action}\n\nGenAI action: {step.genai_action}\n\nAutomation: {step.automation or 'No OS automation for this step.'}")
        command.set(step.command or "")

    def copy_command() -> None:
        root.clipboard_clear()
        root.clipboard_append(command.get())
        messagebox.showinfo("Command copied", "The command template was copied to the clipboard.")

    def open_url() -> None:
        step = WORKFLOW_STEPS[selected.get()]
        if step.url:
            webbrowser.open(step.url)
        else:
            messagebox.showinfo("No URL", "This step does not have a URL to open.")

    def run_safe_action() -> None:
        step = WORKFLOW_STEPS[selected.get()]
        if "Visual Studio" in step.title:
            messagebox.showinfo("Safe action", _launch_visual_studio())
        elif step.url:
            webbrowser.open(step.url)
            copy_command()
        else:
            copy_command()

    sidebar = tk.Frame(root, padx=10, pady=10)
    sidebar.pack(side=tk.LEFT, fill=tk.Y)
    for idx, step in enumerate(WORKFLOW_STEPS):
        tk.Radiobutton(sidebar, text=step.title, variable=selected, value=idx, command=render, anchor="w", justify="left").pack(fill=tk.X)

    content = tk.Frame(root, padx=16, pady=16)
    content.pack(side=tk.RIGHT, expand=True, fill=tk.BOTH)
    tk.Label(content, textvariable=title, font=("Segoe UI", 16, "bold"), anchor="w").pack(fill=tk.X)
    tk.Message(content, textvariable=body, width=650, font=("Segoe UI", 10)).pack(fill=tk.X, pady=12)
    tk.Label(content, text="Command template", anchor="w", font=("Segoe UI", 10, "bold")).pack(fill=tk.X)
    tk.Entry(content, textvariable=command).pack(fill=tk.X, pady=6)
    buttons = tk.Frame(content)
    buttons.pack(fill=tk.X, pady=8)
    tk.Button(buttons, text="Copy command", command=copy_command).pack(side=tk.LEFT, padx=4)
    tk.Button(buttons, text="Open documentation", command=open_url).pack(side=tk.LEFT, padx=4)
    tk.Button(buttons, text="Run safe OS action", command=run_safe_action).pack(side=tk.LEFT, padx=4)
    tk.Message(
        content,
        width=650,
        text="Safety: this guide only performs user-triggered OS actions. It never reads secrets, pushes code, merges PRs, or controls the desktop without an explicit click.",
        fg="darkred",
    ).pack(fill=tk.X, pady=20)

    render()
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(run_app())
